### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by luosss** [zhangjh/node_tumblr_spider#2]
报错了，这是什么问题啊。大神

 node_tumblr_spider@1.0.0 start G:\github file\node_tumblr_spider-master
> cd bin && node main.js

Starting url: https://api.tumblr.com/v2/blog/mjj1024.tumblr.com/posts/video?api_key=rubC6NTRYd6rMMqWIjMFaV213yMtxEGVHYF8TLn6HHfmQoo2VL&reblog_info=true
https://api.tumblr.com/v2/blog/mjj1024.tumblr.com/posts/video?api_key=rubC6NTRYd6rMMqWIjMFaV213yMtxEGVHYF8TLn6HHfmQoo2VL&reblog_info=true
Error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379

**Comment by zhangjh** [comment]
Error Error: Redis connection to localhost:6379 failed 
需要redis服务的，你的redis启动了吗？可以看下文档用法环境依赖一节

**Comment by luosss** [comment]
哦，原来如此，我看看@zhangjh
